#!/bin/bash

ALLCOLS=$(
COLS=""
cat /setup/keyboard-layout.list | while read layout description; do
  description=$(echo ${description} | tr " " "_")
  echo "${layout} ${description}"
done)

KEYBOARD_LAYOUT="$(yad --width 600 --height 600 --list \
  --title 'Keyboard Layout' --column 'Keyboard Layout' \
  --column '' ${ALLCOLS} --print-column 1 --button gtk-ok \
  --image /usr/share/icons/Adwaita/48x48/apps/preferences-desktop-keyboard-symbolic.symbolic.png \
  --text 'Please select a keyboard layout')"

KEYBOARD_LAYOUT=$(echo ${KEYBOARD_LAYOUT} | tr -d '|')

gsettings set org.gnome.desktop.input-sources sources "[('xkb', '${KEYBOARD_LAYOUT}')]"

echo "${KEYBOARD_LAYOUT}" > /tmp/keyboard-layout.selected
